(() => {
  const $ = (s,c=document)=>c.querySelector(s);
  const $$ = (s,c=document)=>[...c.querySelectorAll(s)];
  const esc = (v='')=>String(v).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
  const clone = v => typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v));
  const id = prefix => `${prefix}-${crypto.randomUUID()}`;
  let token = sessionStorage.getItem('empower_admin_token') || '';
  let state = null;
  let current = 'dashboard';
  let dirty = false;
  const defaultHomeGuide={eyebrowEn:'WHERE DO I START?',eyebrowZh:'',title:'If you are facing any of these situations,\nstart with the service that feels most relevant.',items:[{id:'guide-career',icon:'⌁',question:'Unsure what to study or what career direction to take?',description:'Explore your interests, abilities, values and practical options together.',linkText:'Education & Career Counselling →',href:'services.html#career',order:1,active:true},{id:'guide-family',icon:'◎',question:'Is your child becoming less willing to communicate?',description:'Understand emotional needs and communication patterns within the parent–child relationship.',linkText:'Parent–Child Counselling →',href:'services.html#family',order:2,active:true},{id:'guide-couple',icon:'∞',question:'Are repeated arguments making the relationship exhausting?',description:'Create space for both partners to slow down, listen and understand each other.',linkText:'Couple Counselling →',href:'services.html#couple',order:3,active:true},{id:'guide-individual',icon:'◌',question:'Feeling anxious, low or under significant stress lately?',description:'Start with the feelings and daily impact that are affecting you most right now.',linkText:'Individual Counselling →',href:'services.html#individual',order:4,active:true}]};

  const titles={dashboard:'Dashboard',settings:'Website & Contact',homeguide:'Home Guide',counsellor:'Counsellor Profile',services:'Counselling Services',programs:'Programmes & Events',requests:'Bookings & Enquiries',videos:'Resources',media:'Media Library'};
  const loginView=$('#loginView'),appView=$('#appView'),content=$('#content'),sectionTitle=$('#sectionTitle');

  function toast(msg){const t=$('#toast');t.textContent=msg;t.hidden=false;clearTimeout(toast._t);toast._t=setTimeout(()=>t.hidden=true,2600)}
  function markDirty(v=true){dirty=v;$('#saveState').textContent=v?'Unsaved changes':'Synced'}
  function proxyPath(path){return '/.netlify/functions/api-proxy?path='+encodeURIComponent(path)}
  async function api(path,options={}){
    const headers=new Headers(options.headers||{});
    if(token) headers.set('Authorization',`Bearer ${token}`);
    if(options.body && !(options.body instanceof FormData) && !headers.has('Content-Type')) headers.set('Content-Type','application/json');
    let res;
    try{res=await fetch(proxyPath(path),{...options,headers});}
    catch{throw new Error('Unable to connect to the website service. Check that both the Admin and Public sites are deployed correctly.');}
    const raw=await res.text();
    let data={};
    try{data=raw?JSON.parse(raw):{}}catch{data={};}
    if(res.status===401){logout(false);throw new Error(data.error||'Incorrect email/password, or your session has expired.');}
    if(res.status===502) throw new Error(data.error||'The Admin site cannot currently connect to the Public site API.');
    if(!res.ok){
      const fallback=res.status===404
        ? 'The Public website API could not be found. Confirm that the latest Public site version is deployed.'
        : res.status===400
          ? 'The request is incomplete. Check the entered information and try again.'
          : res.status===503
            ? 'The website service is not fully configured. Check the Public site environment variables.'
            : `Request failed (${res.status})`;
      throw new Error(data.error||fallback);
    }
    return data;
  }
  async function login(email,password){const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})});token=r.token;sessionStorage.setItem('empower_admin_token',token);await enterApp()}

  async function checkApiConnection(){
    const el=$('#apiStatus');
    if(!el)return;
    el.className='api-status';
    el.textContent='Checking website service connection…';
    try{
      const res=await fetch(proxyPath('/api/health'),{cache:'no-store'});
      const raw=await res.text();
      let data={};try{data=raw?JSON.parse(raw):{}}catch{}
      if(!res.ok)throw new Error();
      const configuredOrigin=res.headers.get('x-empower-api-origin');
      const publicLink=$('#publicSiteLink');
      if(publicLink&&configuredOrigin){publicLink.href=configuredOrigin+'/';publicLink.removeAttribute('aria-disabled');}
      if(data.authConfigured===false){
        el.classList.add('bad');
        el.textContent='✕ Website service connected, but the admin account has not been configured.';
      }else if(data.requestStorage!=='netlify-blobs'){
        el.classList.add('warn');
        el.textContent='✓ Admin sign-in is working. Confirm that the latest Netlify Blobs Public build is deployed.';
      }else{
        el.classList.add('ok');
        el.textContent='✓ Admin, booking and enquiry storage are connected correctly.';
      }
    }catch{
      el.classList.add('bad');
      el.textContent='✕ Unable to connect to the Public website service. Check the GA Public deployment and PUBLIC_API_ORIGIN.';
    }
  }
  function logout(show=true){token='';state=null;sessionStorage.removeItem('empower_admin_token');appView.hidden=true;loginView.hidden=false;window.scrollTo({top:0,left:0,behavior:'instant'});if(show)toast('Signed out')}
  async function enterApp(){
    loginView.hidden=true;appView.hidden=false;current='dashboard';window.scrollTo({top:0,left:0,behavior:'instant'});
    try{state=await api('/api/admin/content');markDirty(false);render();requestAnimationFrame(()=>window.scrollTo({top:0,left:0,behavior:'instant'}));}
    catch(e){logout(false);$('#loginError').textContent=e.message;$('#loginError').hidden=false;}
  }
  async function save(){
    if(!state) return;
    $('#saveState').textContent='Saving…';
    try{const r=await api('/api/admin/content',{method:'PUT',body:JSON.stringify(state)});state=r.content;markDirty(false);toast('Saved and synced to the Public website');render();}
    catch(e){$('#saveState').textContent='Save failed';toast(e.message)}
  }
  const input=(name,label,value='',type='text',extra='')=>`<label>${esc(label)}<input name="${esc(name)}" type="${type}" value="${esc(value??'')}" ${extra}></label>`;
  const textarea=(name,label,value='',extra='')=>`<label>${esc(label)}<textarea name="${esc(name)}" ${extra}>${esc(value??'')}</textarea></label>`;
  const select=(name,label,value,opts)=>`<label>${esc(label)}<select name="${esc(name)}">${opts.map(([v,l])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;
  function fieldValue(form,name){return form.elements[name]?.value?.trim?.()??''}
  function checked(form,name){return Boolean(form.elements[name]?.checked)}

  function render(){sectionTitle.textContent=titles[current]||'Dashboard';$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.section===current));if(!state)return;({dashboard:renderDashboard,settings:renderSettings,homeguide:renderHomeGuide,counsellor:renderCounsellor,services:renderServices,programs:renderPrograms,requests:renderRequests,videos:renderVideos,media:renderMedia}[current]||renderDashboard)()}
  function renderDashboard(){
    const livePrograms=(state.programs||[]).filter(x=>x.published!==false).length;
    content.innerHTML=`<div class="hero-admin"><div><div class="eyebrow" style="color:#bfd2cb">EMPOWER WEBSITE MANAGEMENT</div><h1>Manage website content and visitor communication in one place.</h1><p>Manage Public website content, counselling services, programmes, booking requests and general enquiries. Saved changes are synchronised to the Public website.</p></div><div class="quick"><button class="btn light" data-go="programs">＋ Add Programme</button><button class="btn light" data-go="requests">View Bookings & Enquiries</button></div></div><div class="stats"><div class="stat"><b>${(state.services||[]).filter(x=>x.active!==false).length}</b><span>Published Services</span></div><div class="stat"><b>${livePrograms}</b><span>Published Programmes</span></div><div class="stat"><b id="dashAppointments">—</b><span>Booking Requests</span></div><div class="stat"><b id="dashPending">—</b><span>Pending Bookings</span></div><div class="stat"><b id="dashEnquiries">—</b><span>General Enquiries</span></div><div class="stat"><b>${state.updatedAt?new Date(state.updatedAt).toLocaleDateString('en-MY'):'—'}</b><span>Last Content Sync</span></div></div><div class="panel" style="margin-top:18px"><div class="panel-head"><h3>System Overview</h3></div><p class="help" style="font-size:.9rem;line-height:1.8">Visitors can submit bookings or enquiries from the Public website. The Admin site can search, filter, update and manage these records, as well as maintain services, programmes and website information.</p></div>`;
    loadRequestSummary();
  }
  async function loadRequestSummary(){
    try{const r=await api('/api/admin/requests');const a=r.appointments||[],e=r.enquiries||[];const set=(id,v)=>{const el=$('#'+id);if(el)el.textContent=v};set('dashAppointments',a.length);set('dashPending',a.filter(x=>x.status==='pending').length);set('dashEnquiries',e.length)}catch(err){['dashAppointments','dashPending','dashEnquiries'].forEach(id=>{const el=$('#'+id);if(el)el.textContent='—'});}
  }
  function renderSettings(){const s=state.settings||{};content.innerHTML=`<form id="settingsForm" class="panel"><div class="panel-head"><h3>Website & Contact Settings</h3><button class="btn primary" type="submit">Save Settings</button></div><div class="grid-2">${input('brandName','Brand Name',s.brandName)}${input('serviceArea','Service Area',s.serviceArea)}${input('phone','Phone Number',s.phone)}${input('whatsapp','WhatsApp (digits only)',s.whatsapp)}${input('businessDays','Business Days',s.businessDays,'text','placeholder="e.g. Monday–Saturday"')}${input('businessHours','Business Hours',s.businessHours)}<div class="field full">${textarea('address','Full Address',s.address)}</div>${input('facebook','Facebook (FB) URL',s.facebook,'url','placeholder="https://www.facebook.com/..."')}${input('youtube','YouTube URL',s.youtube,'url')}${input('instagram','Instagram URL',s.instagram,'url')}<label>Appointment Required<select name="appointmentRequired"><option value="true" ${s.appointmentRequired!==false?'selected':''}>Yes</option><option value="false" ${s.appointmentRequired===false?'selected':''}>No</option></select></label><div class="field full">${textarea('homepageTagline','Homepage Headline',s.homepageTagline)}</div><div class="field full">${textarea('homepageIntro','Homepage Introduction',s.homepageIntro)}</div></div></form>`;$('#settingsForm').onsubmit=e=>{e.preventDefault();const f=e.currentTarget;state.settings={...state.settings,brandName:fieldValue(f,'brandName'),serviceArea:fieldValue(f,'serviceArea'),phone:fieldValue(f,'phone'),whatsapp:fieldValue(f,'whatsapp'),businessDays:fieldValue(f,'businessDays'),businessHours:fieldValue(f,'businessHours'),address:fieldValue(f,'address'),facebook:fieldValue(f,'facebook'),youtube:fieldValue(f,'youtube'),instagram:fieldValue(f,'instagram'),appointmentRequired:fieldValue(f,'appointmentRequired')==='true',homepageTagline:fieldValue(f,'homepageTagline'),homepageIntro:fieldValue(f,'homepageIntro')};markDirty();save()}}

  function renderHomeGuide(){
    const g={...defaultHomeGuide,...(state.homeGuide||{})};
    g.items=Array.isArray(state.homeGuide?.items)?state.homeGuide.items:clone(defaultHomeGuide.items);
    state.homeGuide=g;
    const items=[...g.items].sort((a,b)=>(a.order||0)-(b.order||0));
    content.innerHTML=`<form id="homeGuideForm" class="panel"><div class="panel-head"><div><h3>Homepage “Where Do I Start?” Section</h3><div class="help">Controls the section heading and guidance cards shown on the Public homepage. Saved changes sync directly to the homepage.</div></div><button class="btn primary" type="submit">Save Heading</button></div><div class="grid-2">${input('eyebrowEn','Primary Eyebrow',g.eyebrowEn)}${input('eyebrowZh','Secondary Eyebrow (Optional)',g.eyebrowZh)}<div class="field full">${textarea('title','Main Heading (press Enter for a line break)',g.title)}</div></div></form><div class="panel" style="margin-top:18px"><div class="panel-head"><div><h3>Guidance Cards</h3><div class="help">Edit each card’s icon, question, description, button text and link. Cards can also be added, hidden or deleted.</div></div><button class="btn primary" id="addGuide">＋ Add Card</button></div><div class="list">${items.length?items.map(x=>`<div class="list-item"><div class="item-main"><div class="item-title"><span style="font-size:1.35rem;min-width:28px">${esc(x.icon||'•')}</span><b>${esc(x.question||'Untitled Card')}</b><span class="chip ${x.active!==false?'status-on':'status-off'}">${x.active!==false?'Visible':'Hidden'}</span></div><div class="item-sub">${esc(x.description||'')} · ${esc(x.linkText||'Learn More →')}</div></div><div class="item-actions"><button class="icon-btn" data-edit-guide="${esc(x.id)}">Edit</button><button class="icon-btn" data-delete-guide="${esc(x.id)}">Delete</button></div></div>`).join(''):listEmpty('No guidance cards yet.')}</div></div>`;
    $('#homeGuideForm').onsubmit=e=>{e.preventDefault();const f=e.currentTarget;state.homeGuide={...state.homeGuide,eyebrowEn:fieldValue(f,'eyebrowEn'),eyebrowZh:fieldValue(f,'eyebrowZh'),title:fieldValue(f,'title'),items:state.homeGuide.items||[]};markDirty();save()};
    $('#addGuide').onclick=()=>guideModal();
    $$('[data-edit-guide]').forEach(b=>b.onclick=()=>guideModal((state.homeGuide.items||[]).find(x=>x.id===b.dataset.editGuide)));
    $$('[data-delete-guide]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this homepage guidance card?'))return;state.homeGuide.items=(state.homeGuide.items||[]).filter(x=>x.id!==b.dataset.deleteGuide);markDirty();await save()});
  }
  function guideModal(item={}){
    const total=(state.homeGuide?.items||[]).length;
    openModal(item.id?'Edit Guidance Card':'Add Guidance Card',`<div class="grid-2">${input('icon','Icon / Symbol',item.icon||'•')}${input('order','Order',item.order||total+1,'number')}<div class="field full">${input('question','Question / Title',item.question||'')}</div><div class="field full">${textarea('description','Description',item.description||'')}</div>${input('linkText','Link Text',item.linkText||'Learn More →')}<div class="field full">${input('facebookArticleUrl','Facebook Related Article URL (Optional)',item.facebookArticleUrl||item.facebookUrl||item.fbUrl||item.articleUrl||'','url','placeholder="https://www.facebook.com/..."')}<div class="help">If provided, this card opens the Facebook article. If left blank, it automatically uses the Link Target below.</div></div>${input('href','Link Target / Fallback',item.href||'services.html','text','placeholder="e.g. services.html#career"')}${select('active','Public Visibility',item.active!==false?'true':'false',[['true','Visible'],['false','Hidden']])}</div><div class="actions"><button class="btn primary" type="submit">Save Card</button></div>`,f=>{
      const next={...item,id:item.id||id('guide'),icon:fieldValue(f,'icon')||'•',question:fieldValue(f,'question'),description:fieldValue(f,'description'),linkText:fieldValue(f,'linkText')||'Learn More →',facebookArticleUrl:fieldValue(f,'facebookArticleUrl'),href:fieldValue(f,'href')||'services.html',order:Number(fieldValue(f,'order')||0),active:fieldValue(f,'active')==='true'};
      state.homeGuide=state.homeGuide||clone(defaultHomeGuide);state.homeGuide.items=state.homeGuide.items||[];const i=state.homeGuide.items.findIndex(x=>x.id===next.id);if(i>=0)state.homeGuide.items[i]=next;else state.homeGuide.items.push(next);markDirty();save();closeModal();
    });
  }
  function renderCounsellor(){const c=state.counsellor||{};content.innerHTML=`<form id="counsellorForm" class="panel"><div class="panel-head"><h3>Benson Lim Counsellor Profile</h3><button class="btn primary" type="submit">Save Profile</button></div><div class="photo-row"><div class="photo-preview" id="profilePreview">${c.photoUrl?`<img src="${esc(c.photoUrl)}" alt="">`:'No photo uploaded'}</div><div><div class="upload-wrap"><label class="btn light file-btn">Upload Professional Photo<input type="file" id="profileFile" accept="image/jpeg,image/png,image/webp,image/gif"></label><span class="help">A portrait-format professional photo is recommended. Maximum file size: 6 MB.</span></div><input type="hidden" name="photoUrl" value="${esc(c.photoUrl||'')}"></div></div><div class="grid-2" style="margin-top:22px">${input('nameZh','Display Name',c.nameZh)}${input('nameEn','English Name',c.nameEn)}${input('titleZh','Professional Title',c.titleZh)}<div></div><div class="field full">${textarea('intro','Introduction',c.intro)}</div><div class="field full">${textarea('intro2','Additional Introduction',c.intro2)}</div><div class="field full">${textarea('philosophy','Counselling Approach',c.philosophy)}</div><div class="field full">${textarea('quote','Personal Quote',c.quote)}</div><div class="field full">${textarea('specialities','Areas of Focus (one per line)',(c.specialities||[]).join('\n'))}</div><div class="field full">${textarea('credentials','Professional Qualifications / Background (one per line)',(c.credentials||[]).join('\n'))}</div></div></form>`;
    $('#profileFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const url=await upload(file);$('#counsellorForm').elements.photoUrl.value=url;$('#profilePreview').innerHTML=`<img src="${esc(url)}" alt="">`;toast('Photo uploaded. Remember to save the profile.')}catch(err){toast(err.message)}};
    $('#counsellorForm').onsubmit=e=>{e.preventDefault();const f=e.currentTarget;state.counsellor={...state.counsellor,nameZh:fieldValue(f,'nameZh'),nameEn:fieldValue(f,'nameEn'),titleZh:fieldValue(f,'titleZh'),photoUrl:fieldValue(f,'photoUrl'),intro:fieldValue(f,'intro'),intro2:fieldValue(f,'intro2'),philosophy:fieldValue(f,'philosophy'),quote:fieldValue(f,'quote'),specialities:fieldValue(f,'specialities').split('\n').map(x=>x.trim()).filter(Boolean),credentials:fieldValue(f,'credentials').split('\n').map(x=>x.trim()).filter(Boolean)};markDirty();save()}
  }
  function listEmpty(text){return `<div class="empty">${esc(text)}</div>`}
  function renderServices(){const items=(state.services||[]).sort((a,b)=>(a.order||0)-(b.order||0));content.innerHTML=`<div class="panel"><div class="panel-head"><div><h3>Counselling Services</h3><div class="help">When visibility is turned off, the service will not appear on the Public website.</div></div><button class="btn primary" id="addService">＋ Add Service</button></div><div class="list">${items.length?items.map(s=>`<div class="item-card"><div><h4>${esc(s.title)}</h4><p>${esc(s.shortDescription||'')}</p><div class="chips"><span class="chip">Order ${esc(s.order||0)}</span><span class="chip ${s.active!==false?'status-on':'status-off'}">${s.active!==false?'Visible':'Hidden'}</span></div></div><div class="item-actions"><button class="icon-btn" data-edit-service="${esc(s.id)}">Edit</button><button class="icon-btn" data-delete-service="${esc(s.id)}">Delete</button></div></div>`).join(''):listEmpty('No services yet.')}</div></div>`;$('#addService').onclick=()=>serviceModal();$$('[data-edit-service]').forEach(b=>b.onclick=()=>serviceModal(items.find(x=>x.id===b.dataset.editService)));$$('[data-delete-service]').forEach(b=>b.onclick=()=>removeEntity('services',b.dataset.deleteService,'service'))}
  function serviceModal(item={}){openModal(item.id?'Edit Counselling Service':'Add Counselling Service',`<div class="grid-2">${input('title','Service Name',item.title)}${input('slug','URL Slug',item.slug||'')}${input('order','Order',item.order||((state.services?.length||0)+1),'number')}${select('active','Public Visibility',item.active!==false?'true':'false',[['true','Visible'],['false','Hidden']])}<div class="field full">${textarea('shortDescription','Card Summary',item.shortDescription)}</div><div class="field full">${textarea('description','Full Description',item.description)}</div><div class="field full">${textarea('topics','Related Topics (one per line)',(item.topics||[]).join('\n'))}</div></div><div class="actions"><button class="btn primary" type="submit">Save Service</button></div>`,f=>{const next={...item,id:item.id||id('svc'),title:fieldValue(f,'title'),slug:fieldValue(f,'slug')||fieldValue(f,'title').toLowerCase().replace(/\s+/g,'-'),order:Number(fieldValue(f,'order')||0),active:fieldValue(f,'active')==='true',shortDescription:fieldValue(f,'shortDescription'),description:fieldValue(f,'description'),topics:fieldValue(f,'topics').split('\n').map(x=>x.trim()).filter(Boolean)};upsert('services',next);save();closeModal()})}
  function renderPrograms(){const items=[...(state.programs||[])].sort((a,b)=>String(b.startDate||'').localeCompare(String(a.startDate||'')));content.innerHTML=`<div class="panel"><div class="panel-head"><div><h3>Programmes & Events</h3><div class="help">Published programmes appear on the Public website immediately. Unpublished programmes remain saved in Admin only.</div></div><button class="btn primary" id="addProgram">＋ Add Programme</button></div><div class="list">${items.length?items.map(p=>`<div class="item-card"><div><h4>${esc(p.title)}</h4><p>${esc([categoryText(p.category),p.startDate,p.timeText,p.venue].filter(Boolean).join(' · '))}</p><div class="chips"><span class="chip">${esc(statusText(p.status))}</span><span class="chip ${p.published!==false?'status-on':'status-off'}">${p.published!==false?'Published':'Unpublished'}</span>${p.featured?'<span class="chip">Homepage Featured</span>':''}</div></div><div class="item-actions"><button class="icon-btn" data-edit-program="${esc(p.id)}">Edit</button><button class="icon-btn" data-delete-program="${esc(p.id)}">Delete</button></div></div>`).join(''):listEmpty('No programmes yet. Use “Add Programme” to create one.')}</div></div>`;$('#addProgram').onclick=()=>programModal();$$('[data-edit-program]').forEach(b=>b.onclick=()=>programModal(items.find(x=>x.id===b.dataset.editProgram)));$$('[data-delete-program]').forEach(b=>b.onclick=()=>removeEntity('programs',b.dataset.deleteProgram,'programme'))}
  function categoryText(v){return({training:'Training',workshop:'Workshop',talk:'Talk'})[v]||v||'Event'}function statusText(v){return({open:'Open for Registration',full:'Fully Booked',completed:'Completed'})[v]||'Open for Registration'}
  function programModal(item={}){openModal(item.id?'Edit Programme / Event':'Add Programme / Event',`<div class="grid-2">${input('title','Programme / Event Name',item.title)}${input('slug','URL Slug',item.slug||'')}${select('category','Type',item.category||'workshop',[['training','Training'],['workshop','Workshop'],['talk','Talk']])}${select('status','Registration Status',item.status||'open',[['open','Open for Registration'],['full','Fully Booked'],['completed','Completed']])}${input('startDate','Date',item.startDate||'','date')}${input('timeText','Time',item.timeText||'')}${input('venue','Venue',item.venue||'')}${input('fee','Fee',item.fee||'')}${input('registrationUrl','Registration URL',item.registrationUrl||'','url')}<label>Publication Status<select name="published"><option value="true" ${item.published!==false?'selected':''}>Publish to Website</option><option value="false" ${item.published===false?'selected':''}>Save in Admin Only</option></select></label><label>Homepage Featured<select name="featured"><option value="false" ${!item.featured?'selected':''}>No</option><option value="true" ${item.featured?'selected':''}>Yes</option></select></label><div></div><div class="field full"><label>Cover Image<div class="upload-wrap"><input name="coverImageUrl" value="${esc(item.coverImageUrl||'')}" placeholder="Filled automatically after upload"><label class="btn light file-btn">Upload Image<input type="file" id="programFile" accept="image/jpeg,image/png,image/webp,image/gif"></label></div></label></div><div class="field full">${input('imageAlt','Image Alt Text',item.imageAlt||'')}</div><div class="field full">${textarea('summary','Card Summary',item.summary||'')}</div><div class="field full">${textarea('description','Full Description',item.description||'')}</div></div><div class="actions"><button class="btn primary" type="submit">Save Programme</button></div>`,async f=>{const next={...item,id:item.id||id('program'),title:fieldValue(f,'title'),slug:fieldValue(f,'slug')||fieldValue(f,'title').toLowerCase().replace(/\s+/g,'-'),category:fieldValue(f,'category'),status:fieldValue(f,'status'),startDate:fieldValue(f,'startDate'),timeText:fieldValue(f,'timeText'),venue:fieldValue(f,'venue'),fee:fieldValue(f,'fee'),registrationUrl:fieldValue(f,'registrationUrl'),published:fieldValue(f,'published')==='true',featured:fieldValue(f,'featured')==='true',coverImageUrl:fieldValue(f,'coverImageUrl'),imageAlt:fieldValue(f,'imageAlt'),summary:fieldValue(f,'summary'),description:fieldValue(f,'description'),updatedAt:new Date().toISOString()};upsert('programs',next);await save();closeModal()});setTimeout(()=>{const fi=$('#programFile');if(fi)fi.onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const url=await upload(file);$('#modalForm').elements.coverImageUrl.value=url;toast('Cover image uploaded')}catch(err){toast(err.message)}}},0)}
  function renderVideos(){const items=[...(state.videos||[])].sort((a,b)=>(a.order||0)-(b.order||0));content.innerHTML=`<div class="panel"><div class="panel-head"><div><h3>Resources</h3><div class="help">Add a YouTube link to update the Public resources page.</div></div><button class="btn primary" id="addVideo">＋ Add Video</button></div><div class="list">${items.length?items.map(v=>`<div class="item-card"><div><h4>${esc(v.title)}</h4><p>${esc(v.youtubeUrl||'')}</p><div class="chips"><span class="chip">Order ${esc(v.order||0)}</span><span class="chip ${v.active!==false?'status-on':'status-off'}">${v.active!==false?'Visible':'Hidden'}</span></div></div><div class="item-actions"><button class="icon-btn" data-edit-video="${esc(v.id)}">Edit</button><button class="icon-btn" data-delete-video="${esc(v.id)}">Delete</button></div></div>`).join(''):listEmpty('No videos yet.')}</div></div>`;$('#addVideo').onclick=()=>videoModal();$$('[data-edit-video]').forEach(b=>b.onclick=()=>videoModal(items.find(x=>x.id===b.dataset.editVideo)));$$('[data-delete-video]').forEach(b=>b.onclick=()=>removeEntity('videos',b.dataset.deleteVideo,'video'))}
  function videoModal(item={}){openModal(item.id?'Edit Video':'Add Video',`<div class="grid-2">${input('title','Video Title',item.title)}${input('order','Order',item.order||((state.videos?.length||0)+1),'number')}<div class="field full">${input('youtubeUrl','YouTube URL',item.youtubeUrl||'','url')}</div>${input('category','Category',item.category||'')}${select('active','Public Visibility',item.active!==false?'true':'false',[['true','Visible'],['false','Hidden']])}<div class="field full">${textarea('description','Introduction',item.description||'')}</div></div><div class="actions"><button class="btn primary" type="submit">Save Video</button></div>`,f=>{const next={...item,id:item.id||id('video'),title:fieldValue(f,'title'),youtubeUrl:fieldValue(f,'youtubeUrl'),category:fieldValue(f,'category'),description:fieldValue(f,'description'),order:Number(fieldValue(f,'order')||0),active:fieldValue(f,'active')==='true'};upsert('videos',next);save();closeModal()})}
  async function renderRequests(){
    content.innerHTML=`<div class="panel"><div class="panel-head"><div><h3>Bookings & Enquiries</h3><div class="help">Manage bookings and enquiries submitted from the Public website. Search, filter, sort, update statuses or delete records that are no longer needed.</div></div><button class="btn light" id="refreshRequests">Refresh</button></div><div class="request-toolbar"><label>Search<input id="requestSearch" type="search" placeholder="Name, email, phone, service or subject"></label><label>Type<select id="requestType"><option value="all">All</option><option value="appointment">Booking</option><option value="enquiry">Enquiry</option></select></label><label>Status<select id="requestStatus"><option value="all">All Statuses</option><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="new">New</option><option value="in_progress">In Progress</option><option value="resolved">Resolved</option></select></label><label>Order<select id="requestSort"><option value="newest">Newest → Oldest</option><option value="oldest">Oldest → Newest</option></select></label></div><div id="requestSummary" class="request-summary"></div><div id="requestList" class="request-list"><div class="empty">Loading bookings and enquiries…</div></div></div>`;
    $('#refreshRequests').onclick=renderRequests;
    try{
      const data=await api('/api/admin/requests');
      const appointments=(data.appointments||[]).map(x=>({...x,_type:'appointment'}));
      const enquiries=(data.enquiries||[]).map(x=>({...x,_type:'enquiry'}));
      const all=[...appointments,...enquiries];
      const search=$('#requestSearch'),type=$('#requestType'),status=$('#requestStatus'),sort=$('#requestSort'),list=$('#requestList'),summary=$('#requestSummary');
      const labelStatus=v=>({pending:'Pending',confirmed:'Confirmed',completed:'Completed',cancelled:'Cancelled',new:'New',in_progress:'In Progress',resolved:'Resolved'})[v]||v;
      const statusOptions=item=>item._type==='appointment'?[['pending','Pending'],['confirmed','Confirmed'],['completed','Completed'],['cancelled','Cancelled']]:[['new','New'],['in_progress','In Progress'],['resolved','Resolved']];
      const draw=()=>{
        const term=(search.value||'').trim().toLowerCase(),tv=type.value,sv=status.value,sortValue=sort.value;
        const filtered=all.filter(x=>{const hay=x._type==='appointment'?[x.full_name,x.email,x.phone,x.service_label,x.inquiry_type,x.note]:[x.name,x.email,x.phone,x.subject,x.message];const text=hay.filter(Boolean).join(' ').toLowerCase();return(!term||text.includes(term))&&(tv==='all'||x._type===tv)&&(sv==='all'||x.status===sv)});
        const visible=[...filtered].sort((a,b)=>{const av=String(a.created_at||''),bv=String(b.created_at||'');return sortValue==='oldest'?av.localeCompare(bv):bv.localeCompare(av)});
        summary.textContent=`Showing ${visible.length} / ${all.length} items · Bookings ${appointments.length} · Enquiries ${enquiries.length} · ${sortValue==='oldest'?'Oldest first':'Newest first'}`;
        list.innerHTML=visible.length?visible.map(x=>{const isA=x._type==='appointment',name=isA?x.full_name:x.name,title=isA?(x.service_label||'Booking Requests'):(x.subject||'General Enquiries'),meta=isA?[x.inquiry_type,x.preferred_date,x.preferred_time].filter(Boolean).join(' · '):[x.email,x.phone].filter(Boolean).join(' · '),detail=isA?(x.note||'No note provided'):(x.message||'No message content');return `<article class="request-card"><div class="request-main"><div class="request-kicker">${isA?'Booking Requests':'General Enquiries'} · ${esc(new Date(x.created_at).toLocaleString('en-MY'))}</div><h4>${esc(name||'—')}</h4><b>${esc(title)}</b><p>${esc(meta||'')}</p><p class="request-contact">${esc([x.email,x.phone].filter(Boolean).join(' · '))}</p><details><summary>View Details</summary><p>${esc(detail)}</p></details></div><div class="request-actions"><label>Status<select data-request-status="${esc(x.id)}" data-type="${x._type}">${statusOptions(x).map(([v,l])=>`<option value="${v}" ${x.status===v?'selected':''}>${l}</option>`).join('')}</select></label><button class="btn danger" data-request-delete="${esc(x.id)}" data-type="${x._type}">Delete</button></div></article>`}).join(''):listEmpty('No records match the current filters.');
        $$('[data-request-status]').forEach(sel=>sel.onchange=async()=>{const original=all.find(x=>x.id===sel.dataset.requestStatus&&x._type===sel.dataset.type);try{await api('/api/admin/requests',{method:'PATCH',body:JSON.stringify({type:sel.dataset.type,id:sel.dataset.requestStatus,status:sel.value})});if(original)original.status=sel.value;toast('Status updated');draw()}catch(err){toast(err.message);if(original)sel.value=original.status}});
        $$('[data-request-delete]').forEach(btn=>btn.onclick=async()=>{if(!confirm('Delete this record? This action cannot be undone.'))return;try{await api('/api/admin/requests?type='+encodeURIComponent(btn.dataset.type)+'&id='+encodeURIComponent(btn.dataset.requestDelete),{method:'DELETE'});const i=all.findIndex(x=>x.id===btn.dataset.requestDelete&&x._type===btn.dataset.type);if(i>=0)all.splice(i,1);toast('Record deleted');draw()}catch(err){toast(err.message)}});
      };
      [search,type,status,sort].forEach(el=>el.addEventListener(el.tagName==='INPUT'?'input':'change',draw));draw();
    }catch(err){$('#requestList').innerHTML=listEmpty(err.message)}
  }
  async function renderMedia(){content.innerHTML=`<div class="panel"><div class="panel-head"><div><h3>Media Library</h3><div class="help">Uploaded images can be used for the counsellor profile or programme covers. Before deleting an image, make sure it is no longer referenced by website content.</div></div><label class="btn primary file-btn">＋ Upload Images<input type="file" id="mediaUpload" accept="image/jpeg,image/png,image/webp,image/gif" multiple></label></div><div id="mediaGrid" class="media-grid"><div class="empty">Loading media…</div></div></div>`;$('#mediaUpload').onchange=async e=>{for(const file of [...e.target.files]){try{await upload(file)}catch(err){toast(err.message)}}renderMedia()};try{const r=await api('/api/admin/media');const g=$('#mediaGrid');g.innerHTML=r.items?.length?r.items.map(m=>`<div class="media-item"><img src="${esc(m.url?.startsWith('/api/')?proxyPath(m.url):m.url)}" alt=""><div><button class="icon-btn" data-copy-media="${esc(m.url)}">Copy Link</button><button class="icon-btn" data-delete-media="${esc(m.key)}">Delete</button></div></div>`).join(''):listEmpty('No images uploaded yet.');$$('[data-copy-media]').forEach(b=>b.onclick=()=>navigator.clipboard.writeText(b.dataset.copyMedia).then(()=>toast('Image link copied')));$$('[data-delete-media]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this image? If the website still references it, the image will no longer display.'))return;await api('/api/admin/media?key='+encodeURIComponent(b.dataset.deleteMedia),{method:'DELETE'});renderMedia()})}catch(e){$('#mediaGrid').innerHTML=listEmpty(e.message)}}
  async function upload(file){const form=new FormData();form.append('file',file);const r=await api('/api/admin/upload',{method:'POST',body:form});return r.url}
  function upsert(key,item){state[key]=state[key]||[];const i=state[key].findIndex(x=>x.id===item.id);if(i>=0)state[key][i]=item;else state[key].push(item);markDirty();render()}
  async function removeEntity(key,itemId,label){if(!confirm(`Delete this ${label}?`))return;state[key]=(state[key]||[]).filter(x=>x.id!==itemId);markDirty();await save()}
  function openModal(title,html,onSubmit){$('#modalTitle').textContent=title;$('#modalForm').innerHTML=html;$('#modal').hidden=false;$('#modalForm').onsubmit=e=>{e.preventDefault();onSubmit(e.currentTarget)}}function closeModal(){$('#modal').hidden=true;$('#modalForm').innerHTML=''}
  function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`empower-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
  async function importBackup(file){const text=await file.text();let data;try{data=JSON.parse(text)}catch{throw new Error('The backup file is not valid JSON.')};if(!data?.settings||!data?.counsellor)throw new Error('The backup format is invalid.');if(!confirm('Importing will overwrite the current Admin content. Continue?'))return;state=data;markDirty();await save()}

  $('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').hidden=true;try{await login($('#loginEmail').value,$('#loginPassword').value)}catch(err){$('#loginError').textContent=err.message;$('#loginError').hidden=false}};
  $('#nav').onclick=e=>{const b=e.target.closest('[data-section]');if(!b)return;current=b.dataset.section;render();$('#sidebar').classList.remove('open')};
  content.onclick=e=>{const b=e.target.closest('[data-go]');if(b){current=b.dataset.go;render()}};
  $('#logoutBtn').onclick=()=>logout();$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};$('#exportBtn').onclick=exportBackup;$('#importInput').onchange=e=>{const f=e.target.files[0];if(f)importBackup(f).catch(err=>toast(err.message));e.target.value=''};
  checkApiConnection();
  if(token) enterApp();
})();
